# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_bio', models.CharField(max_length=2000)),
                ('about_location', models.CharField(max_length=100)),
                ('about_post', models.CharField(max_length=3000)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.User')),
            ],
        ),
    ]
