# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_options',
            name='about_post',
        ),
    ]
