# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_remove_user_options_about_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_made', models.CharField(max_length=10000)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.User')),
            ],
        ),
    ]
