# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_posts',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
