# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_user_posts_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
