# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.CharField(max_length=10000)),
                ('msg_content', models.CharField(max_length=10000)),
                ('sent_on', models.DateTimeField(verbose_name='Date Published')),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.User')),
            ],
        ),
    ]
