# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_user_msg_respond_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_view_count', models.IntegerField(default=0)),
                ('user_view_msg', models.CharField(max_length=10000)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.User')),
            ],
        ),
    ]
