# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_user_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_msg',
            name='has_been_read',
            field=models.BooleanField(default=False),
        ),
    ]
