# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-20 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0011_user_msg_has_been_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(default='', max_length=10000)),
                ('sent_on', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Published')),
                ('has_been_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(default=0)),
                ('contact_name', models.CharField(max_length=10000)),
                ('contact_email', models.CharField(max_length=10000)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.User')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='contact_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.Contact'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.User'),
        ),
    ]
