# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0013_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='contact_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.Contact'),
        ),
    ]
