# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-22 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0014_auto_20180420_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='contact_reference',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_reference',
        ),
        migrations.RemoveField(
            model_name='user_msg',
            name='user_reference',
        ),
        migrations.RemoveField(
            model_name='user_view',
            name='user_reference',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='User_Msg',
        ),
        migrations.DeleteModel(
            name='User_View',
        ),
    ]
